/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin-diagnostics'
import { Route as AuthenticatedAdminErrorHealerRouteImport } from './routes/_authenticated/admin-error-healer'
import { Route as AuthenticatedAdminExcelImportRouteImport } from './routes/_authenticated/admin-excel-import'
import { Route as AuthenticatedAdminImageQueueRouteImport } from './routes/_authenticated/admin-image-queue'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin-inventory'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin-orders'
import { Route as AuthenticatedAdminReorderRouteImport } from './routes/_authenticated/admin-reorder'
import { Route as AuthenticatedAiRuntimeRouteImport } from './routes/_authenticated/ai-runtime'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDispensesRouteImport } from './routes/_authenticated/dispenses'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedFamilyHealthRouteImport } from './routes/_authenticated/family-health'
import { Route as AuthenticatedInventoryChatRouteImport } from './routes/_authenticated/inventory-chat'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedMedicalDirectoryRouteImport } from './routes/_authenticated/medical-directory'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient-profile'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSbdmaImportRouteImport } from './routes/_authenticated/sbdma-import'
import { Route as AuthenticatedSeedanceStudioRouteImport } from './routes/_authenticated/seedance-studio'
import { Route as AuthenticatedSegmentsRouteImport } from './routes/_authenticated/segments'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedVisionLabRouteImport } from './routes/_authenticated/vision-lab'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as ApiChatWidgetRouteImport } from './routes/api/chat-widget'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as PlanetPlanetIdRouteImport } from './routes/planet.$planetId'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsBmiRouteImport } from './routes/tools.bmi'
import { Route as ToolsInteractionsRouteImport } from './routes/tools.interactions'
import { Route as ToolsPediatricDoseRouteImport } from './routes/tools.pediatric-dose'
import { Route as ToolsScheduleRouteImport } from './routes/tools.schedule'
import { Route as ToolsSymptomsRouteImport } from './routes/tools.symptoms'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminKernelEvolutionRouteImport } from './routes/_authenticated/admin.kernel-evolution'
import { Route as AuthenticatedAdminPhoenixReportRouteImport } from './routes/_authenticated/admin.phoenix-report'
import { Route as AuthenticatedAdminPrescriptionsRouteImport } from './routes/_authenticated/admin.prescriptions'
import { Route as AuthenticatedAdminSunCoreRouteImport } from './routes/_authenticated/admin.sun-core'
import { Route as AuthenticatedAdminTitanosReportRouteImport } from './routes/_authenticated/admin.titanos-report'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog.index'
import { Route as AuthenticatedCatalogProductIdRouteImport } from './routes/_authenticated/catalog.$productId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedDispensesDispenseIdRouteImport } from './routes/_authenticated/dispenses.$dispenseId'
import { Route as AuthenticatedDoctorsDoctorIdRouteImport } from './routes/_authenticated/doctors.$doctorId'
import { Route as AuthenticatedInsuranceIndexRouteImport } from './routes/_authenticated/insurance.index'
import { Route as AuthenticatedInsuranceClaimsRouteImport } from './routes/_authenticated/insurance.claims'
import { Route as AuthenticatedInsuranceCoverageRouteImport } from './routes/_authenticated/insurance.coverage'
import { Route as AuthenticatedLoyaltyAccountIdRouteImport } from './routes/_authenticated/loyalty.$accountId'
import { Route as AuthenticatedMarketingSocialAssistantRouteImport } from './routes/_authenticated/marketing.social-assistant'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedPrescriptionsPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId'
import { Route as AuthenticatedPromotionsIndexRouteImport } from './routes/_authenticated/promotions.index'
import { Route as AuthenticatedPromotionsIdRouteImport } from './routes/_authenticated/promotions.$id'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders.$id'
import { Route as AuthenticatedPurchasingScanInvoiceRouteImport } from './routes/_authenticated/purchasing.scan-invoice'
import { Route as AuthenticatedStoreCodeRouteImport } from './routes/_authenticated/store.$code'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedInsuranceClaimsClaimIdRouteImport } from './routes/_authenticated/insurance.claims_.$claimId'
import { Route as ApiPublicHooksCrmSyncRetryRouteImport } from './routes/api/public/hooks/crm-sync-retry'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'
import { Route as ApiPublicHooksDlqReprocessorRouteImport } from './routes/api/public/hooks/dlq-reprocessor'
import { Route as ApiPublicHooksEventConsumerRouteImport } from './routes/api/public/hooks/event-consumer'
import { Route as ApiPublicHooksGenerateSocialPostsRouteImport } from './routes/api/public/hooks/generate-social-posts'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/admin-diagnostics',
    path: '/admin-diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminErrorHealerRoute =
  AuthenticatedAdminErrorHealerRouteImport.update({
    id: '/admin-error-healer',
    path: '/admin-error-healer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExcelImportRoute =
  AuthenticatedAdminExcelImportRouteImport.update({
    id: '/admin-excel-import',
    path: '/admin-excel-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImageQueueRoute =
  AuthenticatedAdminImageQueueRouteImport.update({
    id: '/admin-image-queue',
    path: '/admin-image-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/admin-inventory',
    path: '/admin-inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin-orders',
    path: '/admin-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReorderRoute =
  AuthenticatedAdminReorderRouteImport.update({
    id: '/admin-reorder',
    path: '/admin-reorder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiRuntimeRoute = AuthenticatedAiRuntimeRouteImport.update({
  id: '/ai-runtime',
  path: '/ai-runtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispensesRoute = AuthenticatedDispensesRouteImport.update({
  id: '/dispenses',
  path: '/dispenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyHealthRoute =
  AuthenticatedFamilyHealthRouteImport.update({
    id: '/family-health',
    path: '/family-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryChatRoute =
  AuthenticatedInventoryChatRouteImport.update({
    id: '/inventory-chat',
    path: '/inventory-chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicalDirectoryRoute =
  AuthenticatedMedicalDirectoryRouteImport.update({
    id: '/medical-directory',
    path: '/medical-directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/patient-profile',
    path: '/patient-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSbdmaImportRoute =
  AuthenticatedSbdmaImportRouteImport.update({
    id: '/sbdma-import',
    path: '/sbdma-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeedanceStudioRoute =
  AuthenticatedSeedanceStudioRouteImport.update({
    id: '/seedance-studio',
    path: '/seedance-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSegmentsRoute = AuthenticatedSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisionLabRoute = AuthenticatedVisionLabRouteImport.update({
  id: '/vision-lab',
  path: '/vision-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatWidgetRoute = ApiChatWidgetRouteImport.update({
  id: '/api/chat-widget',
  path: '/api/chat-widget',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetPlanetIdRoute = PlanetPlanetIdRouteImport.update({
  id: '/planet/$planetId',
  path: '/planet/$planetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsBmiRoute = ToolsBmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsInteractionsRoute = ToolsInteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPediatricDoseRoute = ToolsPediatricDoseRouteImport.update({
  id: '/pediatric-dose',
  path: '/pediatric-dose',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsScheduleRoute = ToolsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSymptomsRoute = ToolsSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => ToolsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminKernelEvolutionRoute =
  AuthenticatedAdminKernelEvolutionRouteImport.update({
    id: '/admin/kernel-evolution',
    path: '/admin/kernel-evolution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPhoenixReportRoute =
  AuthenticatedAdminPhoenixReportRouteImport.update({
    id: '/admin/phoenix-report',
    path: '/admin/phoenix-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPrescriptionsRoute =
  AuthenticatedAdminPrescriptionsRouteImport.update({
    id: '/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSunCoreRoute =
  AuthenticatedAdminSunCoreRouteImport.update({
    id: '/admin/sun-core',
    path: '/admin/sun-core',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTitanosReportRoute =
  AuthenticatedAdminTitanosReportRouteImport.update({
    id: '/admin/titanos-report',
    path: '/admin/titanos-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductIdRoute =
  AuthenticatedCatalogProductIdRouteImport.update({
    id: '/catalog/$productId',
    path: '/catalog/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedDispensesDispenseIdRoute =
  AuthenticatedDispensesDispenseIdRouteImport.update({
    id: '/$dispenseId',
    path: '/$dispenseId',
    getParentRoute: () => AuthenticatedDispensesRoute,
  } as any)
const AuthenticatedDoctorsDoctorIdRoute =
  AuthenticatedDoctorsDoctorIdRouteImport.update({
    id: '/$doctorId',
    path: '/$doctorId',
    getParentRoute: () => AuthenticatedDoctorsRoute,
  } as any)
const AuthenticatedInsuranceIndexRoute =
  AuthenticatedInsuranceIndexRouteImport.update({
    id: '/insurance/',
    path: '/insurance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceClaimsRoute =
  AuthenticatedInsuranceClaimsRouteImport.update({
    id: '/insurance/claims',
    path: '/insurance/claims',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceCoverageRoute =
  AuthenticatedInsuranceCoverageRouteImport.update({
    id: '/insurance/coverage',
    path: '/insurance/coverage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoyaltyAccountIdRoute =
  AuthenticatedLoyaltyAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedLoyaltyRoute,
  } as any)
const AuthenticatedMarketingSocialAssistantRoute =
  AuthenticatedMarketingSocialAssistantRouteImport.update({
    id: '/marketing/social-assistant',
    path: '/marketing/social-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPrescriptionsPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPromotionsIndexRoute =
  AuthenticatedPromotionsIndexRouteImport.update({
    id: '/promotions/',
    path: '/promotions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsIdRoute =
  AuthenticatedPromotionsIdRouteImport.update({
    id: '/promotions/$id',
    path: '/promotions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchasingScanInvoiceRoute =
  AuthenticatedPurchasingScanInvoiceRouteImport.update({
    id: '/purchasing/scan-invoice',
    path: '/purchasing/scan-invoice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreCodeRoute = AuthenticatedStoreCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AuthenticatedStoreRoute,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInsuranceClaimsClaimIdRoute =
  AuthenticatedInsuranceClaimsClaimIdRouteImport.update({
    id: '/insurance/claims_/$claimId',
    path: '/insurance/claims/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCrmSyncRetryRoute =
  ApiPublicHooksCrmSyncRetryRouteImport.update({
    id: '/api/public/hooks/crm-sync-retry',
    path: '/api/public/hooks/crm-sync-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDlqReprocessorRoute =
  ApiPublicHooksDlqReprocessorRouteImport.update({
    id: '/api/public/hooks/dlq-reprocessor',
    path: '/api/public/hooks/dlq-reprocessor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEventConsumerRoute =
  ApiPublicHooksEventConsumerRouteImport.update({
    id: '/api/public/hooks/event-consumer',
    path: '/api/public/hooks/event-consumer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateSocialPostsRoute =
  ApiPublicHooksGenerateSocialPostsRouteImport.update({
    id: '/api/public/hooks/generate-social-posts',
    path: '/api/public/hooks/generate-social-posts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/mission-control': typeof MissionControlRoute
  '/offline': typeof OfflineRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin-diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin-error-healer': typeof AuthenticatedAdminErrorHealerRoute
  '/admin-excel-import': typeof AuthenticatedAdminExcelImportRoute
  '/admin-image-queue': typeof AuthenticatedAdminImageQueueRoute
  '/admin-inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/admin-reorder': typeof AuthenticatedAdminReorderRoute
  '/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/family-health': typeof AuthenticatedFamilyHealthRoute
  '/inventory-chat': typeof AuthenticatedInventoryChatRoute
  '/loyalty': typeof AuthenticatedLoyaltyRouteWithChildren
  '/medical-directory': typeof AuthenticatedMedicalDirectoryRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/patient-profile': typeof AuthenticatedPatientProfileRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/rewards': typeof AuthenticatedRewardsRoute
  '/sbdma-import': typeof AuthenticatedSbdmaImportRoute
  '/seedance-studio': typeof AuthenticatedSeedanceStudioRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/vision-lab': typeof AuthenticatedVisionLabRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/chat-widget': typeof ApiChatWidgetRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/interactions': typeof ToolsInteractionsRoute
  '/tools/pediatric-dose': typeof ToolsPediatricDoseRoute
  '/tools/schedule': typeof ToolsScheduleRoute
  '/tools/symptoms': typeof ToolsSymptomsRoute
  '/tools/': typeof ToolsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/kernel-evolution': typeof AuthenticatedAdminKernelEvolutionRoute
  '/admin/phoenix-report': typeof AuthenticatedAdminPhoenixReportRoute
  '/admin/prescriptions': typeof AuthenticatedAdminPrescriptionsRoute
  '/admin/sun-core': typeof AuthenticatedAdminSunCoreRoute
  '/admin/titanos-report': typeof AuthenticatedAdminTitanosReportRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/loyalty/$accountId': typeof AuthenticatedLoyaltyAccountIdRoute
  '/marketing/social-assistant': typeof AuthenticatedMarketingSocialAssistantRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/promotions/$id': typeof AuthenticatedPromotionsIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchasing/scan-invoice': typeof AuthenticatedPurchasingScanInvoiceRoute
  '/store/$code': typeof AuthenticatedStoreCodeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/promotions/': typeof AuthenticatedPromotionsIndexRoute
  '/insurance/claims/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
  '/api/public/hooks/crm-sync-retry': typeof ApiPublicHooksCrmSyncRetryRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/dlq-reprocessor': typeof ApiPublicHooksDlqReprocessorRoute
  '/api/public/hooks/event-consumer': typeof ApiPublicHooksEventConsumerRoute
  '/api/public/hooks/generate-social-posts': typeof ApiPublicHooksGenerateSocialPostsRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/mission-control': typeof MissionControlRoute
  '/offline': typeof OfflineRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin-diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin-error-healer': typeof AuthenticatedAdminErrorHealerRoute
  '/admin-excel-import': typeof AuthenticatedAdminExcelImportRoute
  '/admin-image-queue': typeof AuthenticatedAdminImageQueueRoute
  '/admin-inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/admin-reorder': typeof AuthenticatedAdminReorderRoute
  '/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/family-health': typeof AuthenticatedFamilyHealthRoute
  '/inventory-chat': typeof AuthenticatedInventoryChatRoute
  '/loyalty': typeof AuthenticatedLoyaltyRouteWithChildren
  '/medical-directory': typeof AuthenticatedMedicalDirectoryRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/patient-profile': typeof AuthenticatedPatientProfileRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/rewards': typeof AuthenticatedRewardsRoute
  '/sbdma-import': typeof AuthenticatedSbdmaImportRoute
  '/seedance-studio': typeof AuthenticatedSeedanceStudioRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/store': typeof AuthenticatedStoreRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/vision-lab': typeof AuthenticatedVisionLabRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/chat-widget': typeof ApiChatWidgetRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/interactions': typeof ToolsInteractionsRoute
  '/tools/pediatric-dose': typeof ToolsPediatricDoseRoute
  '/tools/schedule': typeof ToolsScheduleRoute
  '/tools/symptoms': typeof ToolsSymptomsRoute
  '/tools': typeof ToolsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/kernel-evolution': typeof AuthenticatedAdminKernelEvolutionRoute
  '/admin/phoenix-report': typeof AuthenticatedAdminPhoenixReportRoute
  '/admin/prescriptions': typeof AuthenticatedAdminPrescriptionsRoute
  '/admin/sun-core': typeof AuthenticatedAdminSunCoreRoute
  '/admin/titanos-report': typeof AuthenticatedAdminTitanosReportRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/loyalty/$accountId': typeof AuthenticatedLoyaltyAccountIdRoute
  '/marketing/social-assistant': typeof AuthenticatedMarketingSocialAssistantRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/promotions/$id': typeof AuthenticatedPromotionsIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchasing/scan-invoice': typeof AuthenticatedPurchasingScanInvoiceRoute
  '/store/$code': typeof AuthenticatedStoreCodeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/insurance': typeof AuthenticatedInsuranceIndexRoute
  '/promotions': typeof AuthenticatedPromotionsIndexRoute
  '/insurance/claims/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
  '/api/public/hooks/crm-sync-retry': typeof ApiPublicHooksCrmSyncRetryRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/dlq-reprocessor': typeof ApiPublicHooksDlqReprocessorRoute
  '/api/public/hooks/event-consumer': typeof ApiPublicHooksEventConsumerRoute
  '/api/public/hooks/generate-social-posts': typeof ApiPublicHooksGenerateSocialPostsRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/mission-control': typeof MissionControlRoute
  '/offline': typeof OfflineRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin-diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin-error-healer': typeof AuthenticatedAdminErrorHealerRoute
  '/_authenticated/admin-excel-import': typeof AuthenticatedAdminExcelImportRoute
  '/_authenticated/admin-image-queue': typeof AuthenticatedAdminImageQueueRoute
  '/_authenticated/admin-inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin-orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin-reorder': typeof AuthenticatedAdminReorderRoute
  '/_authenticated/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/_authenticated/family-health': typeof AuthenticatedFamilyHealthRoute
  '/_authenticated/inventory-chat': typeof AuthenticatedInventoryChatRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRouteWithChildren
  '/_authenticated/medical-directory': typeof AuthenticatedMedicalDirectoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/patient-profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/sbdma-import': typeof AuthenticatedSbdmaImportRoute
  '/_authenticated/seedance-studio': typeof AuthenticatedSeedanceStudioRoute
  '/_authenticated/segments': typeof AuthenticatedSegmentsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/vision-lab': typeof AuthenticatedVisionLabRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/api/chat-widget': typeof ApiChatWidgetRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/product/$handle': typeof ProductHandleRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/tools/bmi': typeof ToolsBmiRoute
  '/tools/interactions': typeof ToolsInteractionsRoute
  '/tools/pediatric-dose': typeof ToolsPediatricDoseRoute
  '/tools/schedule': typeof ToolsScheduleRoute
  '/tools/symptoms': typeof ToolsSymptomsRoute
  '/tools/': typeof ToolsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/kernel-evolution': typeof AuthenticatedAdminKernelEvolutionRoute
  '/_authenticated/admin/phoenix-report': typeof AuthenticatedAdminPhoenixReportRoute
  '/_authenticated/admin/prescriptions': typeof AuthenticatedAdminPrescriptionsRoute
  '/_authenticated/admin/sun-core': typeof AuthenticatedAdminSunCoreRoute
  '/_authenticated/admin/titanos-report': typeof AuthenticatedAdminTitanosReportRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/_authenticated/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/_authenticated/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/_authenticated/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/_authenticated/loyalty/$accountId': typeof AuthenticatedLoyaltyAccountIdRoute
  '/_authenticated/marketing/social-assistant': typeof AuthenticatedMarketingSocialAssistantRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/_authenticated/promotions/$id': typeof AuthenticatedPromotionsIdRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/purchasing/scan-invoice': typeof AuthenticatedPurchasingScanInvoiceRoute
  '/_authenticated/store/$code': typeof AuthenticatedStoreCodeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/_authenticated/promotions/': typeof AuthenticatedPromotionsIndexRoute
  '/_authenticated/insurance/claims_/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
  '/api/public/hooks/crm-sync-retry': typeof ApiPublicHooksCrmSyncRetryRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/dlq-reprocessor': typeof ApiPublicHooksDlqReprocessorRoute
  '/api/public/hooks/event-consumer': typeof ApiPublicHooksEventConsumerRoute
  '/api/public/hooks/generate-social-posts': typeof ApiPublicHooksGenerateSocialPostsRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/mission-control'
    | '/offline'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/tools'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin-diagnostics'
    | '/admin-error-healer'
    | '/admin-excel-import'
    | '/admin-image-queue'
    | '/admin-inventory'
    | '/admin-orders'
    | '/admin-reorder'
    | '/ai-runtime'
    | '/campaigns'
    | '/cart'
    | '/checkout'
    | '/coupons'
    | '/customers'
    | '/dispenses'
    | '/doctors'
    | '/family-health'
    | '/inventory-chat'
    | '/loyalty'
    | '/medical-directory'
    | '/orders'
    | '/patient-profile'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/rewards'
    | '/sbdma-import'
    | '/seedance-studio'
    | '/segments'
    | '/store'
    | '/suppliers'
    | '/vision-lab'
    | '/warehouses'
    | '/api/chat-widget'
    | '/email/unsubscribe'
    | '/planet/$planetId'
    | '/product/$handle'
    | '/product/$productId'
    | '/tools/bmi'
    | '/tools/interactions'
    | '/tools/pediatric-dose'
    | '/tools/schedule'
    | '/tools/symptoms'
    | '/tools/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/kernel-evolution'
    | '/admin/phoenix-report'
    | '/admin/prescriptions'
    | '/admin/sun-core'
    | '/admin/titanos-report'
    | '/campaigns/$id'
    | '/catalog/$productId'
    | '/customers/$customerId'
    | '/dispenses/$dispenseId'
    | '/doctors/$doctorId'
    | '/insurance/claims'
    | '/insurance/coverage'
    | '/loyalty/$accountId'
    | '/marketing/social-assistant'
    | '/orders/$orderId'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/promotions/$id'
    | '/purchase-orders/$id'
    | '/purchasing/scan-invoice'
    | '/store/$code'
    | '/api/public/csp-report'
    | '/lovable/email/suppression'
    | '/analytics/'
    | '/catalog/'
    | '/insurance/'
    | '/promotions/'
    | '/insurance/claims/$claimId'
    | '/api/public/hooks/crm-sync-retry'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/dlq-reprocessor'
    | '/api/public/hooks/event-consumer'
    | '/api/public/hooks/generate-social-posts'
    | '/api/public/hooks/whatsapp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/mission-control'
    | '/offline'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin-diagnostics'
    | '/admin-error-healer'
    | '/admin-excel-import'
    | '/admin-image-queue'
    | '/admin-inventory'
    | '/admin-orders'
    | '/admin-reorder'
    | '/ai-runtime'
    | '/campaigns'
    | '/cart'
    | '/checkout'
    | '/coupons'
    | '/customers'
    | '/dispenses'
    | '/doctors'
    | '/family-health'
    | '/inventory-chat'
    | '/loyalty'
    | '/medical-directory'
    | '/orders'
    | '/patient-profile'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/rewards'
    | '/sbdma-import'
    | '/seedance-studio'
    | '/segments'
    | '/store'
    | '/suppliers'
    | '/vision-lab'
    | '/warehouses'
    | '/api/chat-widget'
    | '/email/unsubscribe'
    | '/planet/$planetId'
    | '/product/$handle'
    | '/product/$productId'
    | '/tools/bmi'
    | '/tools/interactions'
    | '/tools/pediatric-dose'
    | '/tools/schedule'
    | '/tools/symptoms'
    | '/tools'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/kernel-evolution'
    | '/admin/phoenix-report'
    | '/admin/prescriptions'
    | '/admin/sun-core'
    | '/admin/titanos-report'
    | '/campaigns/$id'
    | '/catalog/$productId'
    | '/customers/$customerId'
    | '/dispenses/$dispenseId'
    | '/doctors/$doctorId'
    | '/insurance/claims'
    | '/insurance/coverage'
    | '/loyalty/$accountId'
    | '/marketing/social-assistant'
    | '/orders/$orderId'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/promotions/$id'
    | '/purchase-orders/$id'
    | '/purchasing/scan-invoice'
    | '/store/$code'
    | '/api/public/csp-report'
    | '/lovable/email/suppression'
    | '/analytics'
    | '/catalog'
    | '/insurance'
    | '/promotions'
    | '/insurance/claims/$claimId'
    | '/api/public/hooks/crm-sync-retry'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/dlq-reprocessor'
    | '/api/public/hooks/event-consumer'
    | '/api/public/hooks/generate-social-posts'
    | '/api/public/hooks/whatsapp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/contact'
    | '/mcp'
    | '/mission-control'
    | '/offline'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/shop'
    | '/sitemap.xml'
    | '/tools'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin-diagnostics'
    | '/_authenticated/admin-error-healer'
    | '/_authenticated/admin-excel-import'
    | '/_authenticated/admin-image-queue'
    | '/_authenticated/admin-inventory'
    | '/_authenticated/admin-orders'
    | '/_authenticated/admin-reorder'
    | '/_authenticated/ai-runtime'
    | '/_authenticated/campaigns'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/coupons'
    | '/_authenticated/customers'
    | '/_authenticated/dispenses'
    | '/_authenticated/doctors'
    | '/_authenticated/family-health'
    | '/_authenticated/inventory-chat'
    | '/_authenticated/loyalty'
    | '/_authenticated/medical-directory'
    | '/_authenticated/orders'
    | '/_authenticated/patient-profile'
    | '/_authenticated/patients'
    | '/_authenticated/prescriptions'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/rewards'
    | '/_authenticated/sbdma-import'
    | '/_authenticated/seedance-studio'
    | '/_authenticated/segments'
    | '/_authenticated/store'
    | '/_authenticated/suppliers'
    | '/_authenticated/vision-lab'
    | '/_authenticated/warehouses'
    | '/api/chat-widget'
    | '/email/unsubscribe'
    | '/planet/$planetId'
    | '/product/$handle'
    | '/product/$productId'
    | '/tools/bmi'
    | '/tools/interactions'
    | '/tools/pediatric-dose'
    | '/tools/schedule'
    | '/tools/symptoms'
    | '/tools/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/kernel-evolution'
    | '/_authenticated/admin/phoenix-report'
    | '/_authenticated/admin/prescriptions'
    | '/_authenticated/admin/sun-core'
    | '/_authenticated/admin/titanos-report'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/catalog/$productId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/dispenses/$dispenseId'
    | '/_authenticated/doctors/$doctorId'
    | '/_authenticated/insurance/claims'
    | '/_authenticated/insurance/coverage'
    | '/_authenticated/loyalty/$accountId'
    | '/_authenticated/marketing/social-assistant'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/prescriptions/$prescriptionId'
    | '/_authenticated/promotions/$id'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/purchasing/scan-invoice'
    | '/_authenticated/store/$code'
    | '/api/public/csp-report'
    | '/lovable/email/suppression'
    | '/_authenticated/analytics/'
    | '/_authenticated/catalog/'
    | '/_authenticated/insurance/'
    | '/_authenticated/promotions/'
    | '/_authenticated/insurance/claims_/$claimId'
    | '/api/public/hooks/crm-sync-retry'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/dlq-reprocessor'
    | '/api/public/hooks/event-consumer'
    | '/api/public/hooks/generate-social-posts'
    | '/api/public/hooks/whatsapp'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  MissionControlRoute: typeof MissionControlRoute
  OfflineRoute: typeof OfflineRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatWidgetRoute: typeof ApiChatWidgetRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PlanetPlanetIdRoute: typeof PlanetPlanetIdRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCrmSyncRetryRoute: typeof ApiPublicHooksCrmSyncRetryRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
  ApiPublicHooksDlqReprocessorRoute: typeof ApiPublicHooksDlqReprocessorRoute
  ApiPublicHooksEventConsumerRoute: typeof ApiPublicHooksEventConsumerRoute
  ApiPublicHooksGenerateSocialPostsRoute: typeof ApiPublicHooksGenerateSocialPostsRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-diagnostics': {
      id: '/_authenticated/admin-diagnostics'
      path: '/admin-diagnostics'
      fullPath: '/admin-diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-error-healer': {
      id: '/_authenticated/admin-error-healer'
      path: '/admin-error-healer'
      fullPath: '/admin-error-healer'
      preLoaderRoute: typeof AuthenticatedAdminErrorHealerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-excel-import': {
      id: '/_authenticated/admin-excel-import'
      path: '/admin-excel-import'
      fullPath: '/admin-excel-import'
      preLoaderRoute: typeof AuthenticatedAdminExcelImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-image-queue': {
      id: '/_authenticated/admin-image-queue'
      path: '/admin-image-queue'
      fullPath: '/admin-image-queue'
      preLoaderRoute: typeof AuthenticatedAdminImageQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-inventory': {
      id: '/_authenticated/admin-inventory'
      path: '/admin-inventory'
      fullPath: '/admin-inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-orders': {
      id: '/_authenticated/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-reorder': {
      id: '/_authenticated/admin-reorder'
      path: '/admin-reorder'
      fullPath: '/admin-reorder'
      preLoaderRoute: typeof AuthenticatedAdminReorderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-runtime': {
      id: '/_authenticated/ai-runtime'
      path: '/ai-runtime'
      fullPath: '/ai-runtime'
      preLoaderRoute: typeof AuthenticatedAiRuntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispenses': {
      id: '/_authenticated/dispenses'
      path: '/dispenses'
      fullPath: '/dispenses'
      preLoaderRoute: typeof AuthenticatedDispensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family-health': {
      id: '/_authenticated/family-health'
      path: '/family-health'
      fullPath: '/family-health'
      preLoaderRoute: typeof AuthenticatedFamilyHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory-chat': {
      id: '/_authenticated/inventory-chat'
      path: '/inventory-chat'
      fullPath: '/inventory-chat'
      preLoaderRoute: typeof AuthenticatedInventoryChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medical-directory': {
      id: '/_authenticated/medical-directory'
      path: '/medical-directory'
      fullPath: '/medical-directory'
      preLoaderRoute: typeof AuthenticatedMedicalDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-profile': {
      id: '/_authenticated/patient-profile'
      path: '/patient-profile'
      fullPath: '/patient-profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sbdma-import': {
      id: '/_authenticated/sbdma-import'
      path: '/sbdma-import'
      fullPath: '/sbdma-import'
      preLoaderRoute: typeof AuthenticatedSbdmaImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seedance-studio': {
      id: '/_authenticated/seedance-studio'
      path: '/seedance-studio'
      fullPath: '/seedance-studio'
      preLoaderRoute: typeof AuthenticatedSeedanceStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/segments': {
      id: '/_authenticated/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AuthenticatedSegmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vision-lab': {
      id: '/_authenticated/vision-lab'
      path: '/vision-lab'
      fullPath: '/vision-lab'
      preLoaderRoute: typeof AuthenticatedVisionLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat-widget': {
      id: '/api/chat-widget'
      path: '/api/chat-widget'
      fullPath: '/api/chat-widget'
      preLoaderRoute: typeof ApiChatWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet/$planetId': {
      id: '/planet/$planetId'
      path: '/planet/$planetId'
      fullPath: '/planet/$planetId'
      preLoaderRoute: typeof PlanetPlanetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/bmi': {
      id: '/tools/bmi'
      path: '/bmi'
      fullPath: '/tools/bmi'
      preLoaderRoute: typeof ToolsBmiRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/interactions': {
      id: '/tools/interactions'
      path: '/interactions'
      fullPath: '/tools/interactions'
      preLoaderRoute: typeof ToolsInteractionsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pediatric-dose': {
      id: '/tools/pediatric-dose'
      path: '/pediatric-dose'
      fullPath: '/tools/pediatric-dose'
      preLoaderRoute: typeof ToolsPediatricDoseRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/schedule': {
      id: '/tools/schedule'
      path: '/schedule'
      fullPath: '/tools/schedule'
      preLoaderRoute: typeof ToolsScheduleRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/symptoms': {
      id: '/tools/symptoms'
      path: '/symptoms'
      fullPath: '/tools/symptoms'
      preLoaderRoute: typeof ToolsSymptomsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/kernel-evolution': {
      id: '/_authenticated/admin/kernel-evolution'
      path: '/admin/kernel-evolution'
      fullPath: '/admin/kernel-evolution'
      preLoaderRoute: typeof AuthenticatedAdminKernelEvolutionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/phoenix-report': {
      id: '/_authenticated/admin/phoenix-report'
      path: '/admin/phoenix-report'
      fullPath: '/admin/phoenix-report'
      preLoaderRoute: typeof AuthenticatedAdminPhoenixReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/prescriptions': {
      id: '/_authenticated/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof AuthenticatedAdminPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sun-core': {
      id: '/_authenticated/admin/sun-core'
      path: '/admin/sun-core'
      fullPath: '/admin/sun-core'
      preLoaderRoute: typeof AuthenticatedAdminSunCoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/titanos-report': {
      id: '/_authenticated/admin/titanos-report'
      path: '/admin/titanos-report'
      fullPath: '/admin/titanos-report'
      preLoaderRoute: typeof AuthenticatedAdminTitanosReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/$productId': {
      id: '/_authenticated/catalog/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof AuthenticatedCatalogProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/dispenses/$dispenseId': {
      id: '/_authenticated/dispenses/$dispenseId'
      path: '/$dispenseId'
      fullPath: '/dispenses/$dispenseId'
      preLoaderRoute: typeof AuthenticatedDispensesDispenseIdRouteImport
      parentRoute: typeof AuthenticatedDispensesRoute
    }
    '/_authenticated/doctors/$doctorId': {
      id: '/_authenticated/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof AuthenticatedDoctorsDoctorIdRouteImport
      parentRoute: typeof AuthenticatedDoctorsRoute
    }
    '/_authenticated/insurance/': {
      id: '/_authenticated/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof AuthenticatedInsuranceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance/claims': {
      id: '/_authenticated/insurance/claims'
      path: '/insurance/claims'
      fullPath: '/insurance/claims'
      preLoaderRoute: typeof AuthenticatedInsuranceClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance/coverage': {
      id: '/_authenticated/insurance/coverage'
      path: '/insurance/coverage'
      fullPath: '/insurance/coverage'
      preLoaderRoute: typeof AuthenticatedInsuranceCoverageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty/$accountId': {
      id: '/_authenticated/loyalty/$accountId'
      path: '/$accountId'
      fullPath: '/loyalty/$accountId'
      preLoaderRoute: typeof AuthenticatedLoyaltyAccountIdRouteImport
      parentRoute: typeof AuthenticatedLoyaltyRoute
    }
    '/_authenticated/marketing/social-assistant': {
      id: '/_authenticated/marketing/social-assistant'
      path: '/marketing/social-assistant'
      fullPath: '/marketing/social-assistant'
      preLoaderRoute: typeof AuthenticatedMarketingSocialAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/prescriptions/$prescriptionId': {
      id: '/_authenticated/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/prescriptions/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/promotions/': {
      id: '/_authenticated/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AuthenticatedPromotionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions/$id': {
      id: '/_authenticated/promotions/$id'
      path: '/promotions/$id'
      fullPath: '/promotions/$id'
      preLoaderRoute: typeof AuthenticatedPromotionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersRoute
    }
    '/_authenticated/purchasing/scan-invoice': {
      id: '/_authenticated/purchasing/scan-invoice'
      path: '/purchasing/scan-invoice'
      fullPath: '/purchasing/scan-invoice'
      preLoaderRoute: typeof AuthenticatedPurchasingScanInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store/$code': {
      id: '/_authenticated/store/$code'
      path: '/$code'
      fullPath: '/store/$code'
      preLoaderRoute: typeof AuthenticatedStoreCodeRouteImport
      parentRoute: typeof AuthenticatedStoreRoute
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/insurance/claims_/$claimId': {
      id: '/_authenticated/insurance/claims_/$claimId'
      path: '/insurance/claims/$claimId'
      fullPath: '/insurance/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedInsuranceClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/crm-sync-retry': {
      id: '/api/public/hooks/crm-sync-retry'
      path: '/api/public/hooks/crm-sync-retry'
      fullPath: '/api/public/hooks/crm-sync-retry'
      preLoaderRoute: typeof ApiPublicHooksCrmSyncRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dlq-reprocessor': {
      id: '/api/public/hooks/dlq-reprocessor'
      path: '/api/public/hooks/dlq-reprocessor'
      fullPath: '/api/public/hooks/dlq-reprocessor'
      preLoaderRoute: typeof ApiPublicHooksDlqReprocessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/event-consumer': {
      id: '/api/public/hooks/event-consumer'
      path: '/api/public/hooks/event-consumer'
      fullPath: '/api/public/hooks/event-consumer'
      preLoaderRoute: typeof ApiPublicHooksEventConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-social-posts': {
      id: '/api/public/hooks/generate-social-posts'
      path: '/api/public/hooks/generate-social-posts'
      fullPath: '/api/public/hooks/generate-social-posts'
      preLoaderRoute: typeof ApiPublicHooksGenerateSocialPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCampaignsRouteChildren {
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
}

const AuthenticatedCampaignsRouteChildren: AuthenticatedCampaignsRouteChildren =
  {
    AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  }

const AuthenticatedCampaignsRouteWithChildren =
  AuthenticatedCampaignsRoute._addFileChildren(
    AuthenticatedCampaignsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedDispensesRouteChildren {
  AuthenticatedDispensesDispenseIdRoute: typeof AuthenticatedDispensesDispenseIdRoute
}

const AuthenticatedDispensesRouteChildren: AuthenticatedDispensesRouteChildren =
  {
    AuthenticatedDispensesDispenseIdRoute:
      AuthenticatedDispensesDispenseIdRoute,
  }

const AuthenticatedDispensesRouteWithChildren =
  AuthenticatedDispensesRoute._addFileChildren(
    AuthenticatedDispensesRouteChildren,
  )

interface AuthenticatedDoctorsRouteChildren {
  AuthenticatedDoctorsDoctorIdRoute: typeof AuthenticatedDoctorsDoctorIdRoute
}

const AuthenticatedDoctorsRouteChildren: AuthenticatedDoctorsRouteChildren = {
  AuthenticatedDoctorsDoctorIdRoute: AuthenticatedDoctorsDoctorIdRoute,
}

const AuthenticatedDoctorsRouteWithChildren =
  AuthenticatedDoctorsRoute._addFileChildren(AuthenticatedDoctorsRouteChildren)

interface AuthenticatedLoyaltyRouteChildren {
  AuthenticatedLoyaltyAccountIdRoute: typeof AuthenticatedLoyaltyAccountIdRoute
}

const AuthenticatedLoyaltyRouteChildren: AuthenticatedLoyaltyRouteChildren = {
  AuthenticatedLoyaltyAccountIdRoute: AuthenticatedLoyaltyAccountIdRoute,
}

const AuthenticatedLoyaltyRouteWithChildren =
  AuthenticatedLoyaltyRoute._addFileChildren(AuthenticatedLoyaltyRouteChildren)

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPrescriptionsRouteChildren {
  AuthenticatedPrescriptionsPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRoute
}

const AuthenticatedPrescriptionsRouteChildren: AuthenticatedPrescriptionsRouteChildren =
  {
    AuthenticatedPrescriptionsPrescriptionIdRoute:
      AuthenticatedPrescriptionsPrescriptionIdRoute,
  }

const AuthenticatedPrescriptionsRouteWithChildren =
  AuthenticatedPrescriptionsRoute._addFileChildren(
    AuthenticatedPrescriptionsRouteChildren,
  )

interface AuthenticatedPurchaseOrdersRouteChildren {
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
}

const AuthenticatedPurchaseOrdersRouteChildren: AuthenticatedPurchaseOrdersRouteChildren =
  {
    AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  }

const AuthenticatedPurchaseOrdersRouteWithChildren =
  AuthenticatedPurchaseOrdersRoute._addFileChildren(
    AuthenticatedPurchaseOrdersRouteChildren,
  )

interface AuthenticatedStoreRouteChildren {
  AuthenticatedStoreCodeRoute: typeof AuthenticatedStoreCodeRoute
}

const AuthenticatedStoreRouteChildren: AuthenticatedStoreRouteChildren = {
  AuthenticatedStoreCodeRoute: AuthenticatedStoreCodeRoute,
}

const AuthenticatedStoreRouteWithChildren =
  AuthenticatedStoreRoute._addFileChildren(AuthenticatedStoreRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminErrorHealerRoute: typeof AuthenticatedAdminErrorHealerRoute
  AuthenticatedAdminExcelImportRoute: typeof AuthenticatedAdminExcelImportRoute
  AuthenticatedAdminImageQueueRoute: typeof AuthenticatedAdminImageQueueRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReorderRoute: typeof AuthenticatedAdminReorderRoute
  AuthenticatedAiRuntimeRoute: typeof AuthenticatedAiRuntimeRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDispensesRoute: typeof AuthenticatedDispensesRouteWithChildren
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRouteWithChildren
  AuthenticatedFamilyHealthRoute: typeof AuthenticatedFamilyHealthRoute
  AuthenticatedInventoryChatRoute: typeof AuthenticatedInventoryChatRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRouteWithChildren
  AuthenticatedMedicalDirectoryRoute: typeof AuthenticatedMedicalDirectoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRouteWithChildren
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRouteWithChildren
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSbdmaImportRoute: typeof AuthenticatedSbdmaImportRoute
  AuthenticatedSeedanceStudioRoute: typeof AuthenticatedSeedanceStudioRoute
  AuthenticatedSegmentsRoute: typeof AuthenticatedSegmentsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedVisionLabRoute: typeof AuthenticatedVisionLabRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedAdminKernelEvolutionRoute: typeof AuthenticatedAdminKernelEvolutionRoute
  AuthenticatedAdminPhoenixReportRoute: typeof AuthenticatedAdminPhoenixReportRoute
  AuthenticatedAdminPrescriptionsRoute: typeof AuthenticatedAdminPrescriptionsRoute
  AuthenticatedAdminSunCoreRoute: typeof AuthenticatedAdminSunCoreRoute
  AuthenticatedAdminTitanosReportRoute: typeof AuthenticatedAdminTitanosReportRoute
  AuthenticatedCatalogProductIdRoute: typeof AuthenticatedCatalogProductIdRoute
  AuthenticatedInsuranceClaimsRoute: typeof AuthenticatedInsuranceClaimsRoute
  AuthenticatedInsuranceCoverageRoute: typeof AuthenticatedInsuranceCoverageRoute
  AuthenticatedMarketingSocialAssistantRoute: typeof AuthenticatedMarketingSocialAssistantRoute
  AuthenticatedPromotionsIdRoute: typeof AuthenticatedPromotionsIdRoute
  AuthenticatedPurchasingScanInvoiceRoute: typeof AuthenticatedPurchasingScanInvoiceRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedInsuranceIndexRoute: typeof AuthenticatedInsuranceIndexRoute
  AuthenticatedPromotionsIndexRoute: typeof AuthenticatedPromotionsIndexRoute
  AuthenticatedInsuranceClaimsClaimIdRoute: typeof AuthenticatedInsuranceClaimsClaimIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
  AuthenticatedAdminErrorHealerRoute: AuthenticatedAdminErrorHealerRoute,
  AuthenticatedAdminExcelImportRoute: AuthenticatedAdminExcelImportRoute,
  AuthenticatedAdminImageQueueRoute: AuthenticatedAdminImageQueueRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminReorderRoute: AuthenticatedAdminReorderRoute,
  AuthenticatedAiRuntimeRoute: AuthenticatedAiRuntimeRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDispensesRoute: AuthenticatedDispensesRouteWithChildren,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRouteWithChildren,
  AuthenticatedFamilyHealthRoute: AuthenticatedFamilyHealthRoute,
  AuthenticatedInventoryChatRoute: AuthenticatedInventoryChatRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRouteWithChildren,
  AuthenticatedMedicalDirectoryRoute: AuthenticatedMedicalDirectoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRouteWithChildren,
  AuthenticatedPurchaseOrdersRoute:
    AuthenticatedPurchaseOrdersRouteWithChildren,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSbdmaImportRoute: AuthenticatedSbdmaImportRoute,
  AuthenticatedSeedanceStudioRoute: AuthenticatedSeedanceStudioRoute,
  AuthenticatedSegmentsRoute: AuthenticatedSegmentsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedVisionLabRoute: AuthenticatedVisionLabRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedAdminKernelEvolutionRoute:
    AuthenticatedAdminKernelEvolutionRoute,
  AuthenticatedAdminPhoenixReportRoute: AuthenticatedAdminPhoenixReportRoute,
  AuthenticatedAdminPrescriptionsRoute: AuthenticatedAdminPrescriptionsRoute,
  AuthenticatedAdminSunCoreRoute: AuthenticatedAdminSunCoreRoute,
  AuthenticatedAdminTitanosReportRoute: AuthenticatedAdminTitanosReportRoute,
  AuthenticatedCatalogProductIdRoute: AuthenticatedCatalogProductIdRoute,
  AuthenticatedInsuranceClaimsRoute: AuthenticatedInsuranceClaimsRoute,
  AuthenticatedInsuranceCoverageRoute: AuthenticatedInsuranceCoverageRoute,
  AuthenticatedMarketingSocialAssistantRoute:
    AuthenticatedMarketingSocialAssistantRoute,
  AuthenticatedPromotionsIdRoute: AuthenticatedPromotionsIdRoute,
  AuthenticatedPurchasingScanInvoiceRoute:
    AuthenticatedPurchasingScanInvoiceRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedInsuranceIndexRoute: AuthenticatedInsuranceIndexRoute,
  AuthenticatedPromotionsIndexRoute: AuthenticatedPromotionsIndexRoute,
  AuthenticatedInsuranceClaimsClaimIdRoute:
    AuthenticatedInsuranceClaimsClaimIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ToolsRouteChildren {
  ToolsBmiRoute: typeof ToolsBmiRoute
  ToolsInteractionsRoute: typeof ToolsInteractionsRoute
  ToolsPediatricDoseRoute: typeof ToolsPediatricDoseRoute
  ToolsScheduleRoute: typeof ToolsScheduleRoute
  ToolsSymptomsRoute: typeof ToolsSymptomsRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsBmiRoute: ToolsBmiRoute,
  ToolsInteractionsRoute: ToolsInteractionsRoute,
  ToolsPediatricDoseRoute: ToolsPediatricDoseRoute,
  ToolsScheduleRoute: ToolsScheduleRoute,
  ToolsSymptomsRoute: ToolsSymptomsRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  MissionControlRoute: MissionControlRoute,
  OfflineRoute: OfflineRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatWidgetRoute: ApiChatWidgetRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PlanetPlanetIdRoute: PlanetPlanetIdRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCrmSyncRetryRoute: ApiPublicHooksCrmSyncRetryRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
  ApiPublicHooksDlqReprocessorRoute: ApiPublicHooksDlqReprocessorRoute,
  ApiPublicHooksEventConsumerRoute: ApiPublicHooksEventConsumerRoute,
  ApiPublicHooksGenerateSocialPostsRoute:
    ApiPublicHooksGenerateSocialPostsRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
